

name: 01 - Building Blocks
on: push # this workflow will be triggered when we push code to the repository

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps: 
      - name: Say echo
        run: echo "Hello world"

  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Failed step
        run: |
          echo "I will fail"
          exit 1
    # when a step fails, the whole job and workflow are considered as failed
    # if any step fails, any subsequent steps will not be executed by default
      - name: Say goodbye
        run: echo "Goodbye!"