name: 02 - Workflow events

on: push

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: |
          echo "Event name: ${{ github.event_name }}"
# ${{ github }} this is called github context
