name: 04 - Using Actions 

# Steps to install react application
# npx create-react-app --template typescript react-app   

# this will create the react app in pwd in this folder react-app (useful for starting react)
on: push


    # 0. Checkout the code from the repository
    # 1. Install dependencies of our react application
    # 2. Execute automated tests

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node 
        uses: actions/setup-node@v3 # use this action
        with:
          node-version: '24.*' # with this version

      - name: Print current working directory 
        run: |
          pwd
          ls 04-using-actions
          ls 04-using-actions/react-app
      
      - name: Install dependencies
        run: npm ci 
        working-directory: 04-using-actions/react-app
      

    

