name: 06 - Contexts 
run-name: 06 - Contexts | DEBUG - ${{ inputs.debug }}

on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false
      test_input:
        type: string 
        default: test


jobs:
  echo-data: 
    runs-on: ubuntu-latest
    steps:
      - name: Display information
        run : |
          echo "Event name ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Run ID: ${{ github.workflow }}"
          echo "Run number: ${{ github.run_number }}"

      - name: Retrieve vars
        run: |
          echo "Variable value ${{ vars.MY_VAR }}"